apiVersion: apps/v1
kind: Deployment
metadata:
  name: notif-manager
  namespace: kube-system
  annotations:
    "sidecar.jaegertracing.io/inject": "true"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: notif-manager
  template:
    metadata:
      labels:
        app: notif-manager
    spec:
      containers:
        - name: notif-manager
          image: uhub.service.ucloud.cn/entropypool/notif-manager:latest
          imagePullPolicy: Always
          volumeMounts:
            - name: service-config
              mountPath: /etc/G11nManager
          env:
            - name: ENV_ENVIRONMENT_TARGET
              valueFrom:
                configMapKeyRef:
                  name: system-environment
                  key: environment.target
            - name: ENV_CONSUL_HOST
              valueFrom:
                configMapKeyRef:
                  name: system-environment
                  key: environment.consul_host
            - name: ENV_CONSUL_PORT
              valueFrom:
                configMapKeyRef:
                  name: system-environment
                  key: environment.consul_port
            - name: ENV_CLUSTER_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
      volumes:
        - name: service-config
          configMap:
            name: notif-manager-config
            items:
              - key: service-conf
                path: G11nManager.viper.yaml
---
apiVersion: v1
kind: Service
metadata:
  name: notif-manager
  namespace: kube-system
spec:
  ports:
    - name: http
      port: 50680
      targetPort: 50680
    - name: grpc
      port: 50681
      targetPort: 50681
    - name: healthz
      port: 50682
      targetPort: 50682
    - name: prometheus
      port: 50683
      targetPort: 50683
  selector:
    app: notif-manager
