// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Announcement is the predicate function for announcement builders.
type Announcement func(*sql.Selector)

// Notif is the predicate function for notif builders.
type Notif func(*sql.Selector)

// ReadAnnouncement is the predicate function for readannouncement builders.
type ReadAnnouncement func(*sql.Selector)
