// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Announcement is the predicate function for announcement builders.
type Announcement func(*sql.Selector)

// Notif is the predicate function for notif builders.
type Notif func(*sql.Selector)

// NotifChannel is the predicate function for notifchannel builders.
type NotifChannel func(*sql.Selector)

// ReadAnnouncement is the predicate function for readannouncement builders.
type ReadAnnouncement func(*sql.Selector)

// SendAnnouncement is the predicate function for sendannouncement builders.
type SendAnnouncement func(*sql.Selector)

// TxNotifState is the predicate function for txnotifstate builders.
type TxNotifState func(*sql.Selector)

// UserAnnouncement is the predicate function for userannouncement builders.
type UserAnnouncement func(*sql.Selector)
